### ISSUE TITLE
How to run the code 

### ISSUE THREAD

**Issue by Ofrila** [Cameltr/RGTSI#2]
Thanks.How do we run the code? Do I use python train.py directly? Are there any paths that need to be changed？ And there is no de_root in the train_options.py file. Do we add this by ourselves? What does st_root mean？Sorry,I have too many qusetions. Looking forward to your reply.

**Comment by Cameltr** [comment]
Thank you for your question. Since RGTSI is nearly a year ago, it will take some time to reorganize the code. I will rewrite Readme and retrain and release the model for downloading , which will take several days. You may need to wait for a while. In addition, our new work **TransRef** is still under review. If you find the dataset is useful, you can cite RGTSI in your paper.
